Preparations/Preparation/Controllers/QuestionController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Preparation.Interfaces;
using Preparation.Models;

namespace Preparation.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestion _questionRepository;
        private readonly ISubject _subjectRepository;
        public QuestionController(IQuestion questionRepository, ISubject subjectRepository)
        {
            _questionRepository = questionRepository;
            _subjectRepository = subjectRepository;
        }


        public async Task<IActionResult> Index(string sortExpression = "", string searchText = "", int currentPage = 1, int pageSize = 5)
        {

            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.AddColumn("answer");
            sortModel.AddColumn("subject");
            sortModel.ApplySort(sortExpression);

            PaginatedList<Question> items = await _questionRepository.GetItemsAsync(sortModel.SortedProperty, sortModel.SortedOrder, searchText, currentPage, pageSize);

            var pager = new PagerModel(items.TotalRecords, currentPage, pageSize);
            pager.SortExpression = sortExpression;
            pager.SearchText = searchText;

            ViewBag.Pager = pager;

            ViewData["SortModel"] = sortModel;
            ViewBag.SearchText = searchText;

            TempData["SearchText"] = searchText;
            TempData.Keep("SearchText");

            TempData["PageSize"] = pageSize;
            TempData.Keep("PageSize");

            TempData["CurrentPage"] = currentPage;
            TempData.Keep("CurrentPage");

            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var item = new Question();
            PopulateViewBagsAsync().GetAwaiter().GetResult();

            return View(item);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Question question)
        {
            if (ModelState.IsValid)
            {
                await _questionRepository.GreateAsync(question);
                return RedirectToAction(nameof(Index));
            }
            await PopulateViewBagsAsync();
            return View(question);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var item = await _questionRepository.GetItemAsync(id);
            await PopulateViewBagsAsync();

            if (item != null)
            {
                return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Question question)
        {
            if (ModelState.IsValid)
            {
                await _questionRepository.EditAsync(question);
                return RedirectToAction(nameof(Index));
            }
            await PopulateViewBagsAsync();
            return View(question);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await _questionRepository.GetItemAsync(id);

            if (item != null)
            {
                return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Question question)
        {
            if (ModelState.IsValid)
            {
                await _questionRepository.DeleteAsync(question);
                return RedirectToAction(nameof(Index));
            }

            return View(question);
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var item = await _questionRepository.GetItemAsync(id);

            if (item != null)
            {
                return View(item);
            }

            return NotFound();
        }


        private async Task PopulateViewBagsAsync()
        {
            ViewBag.Subjects = await GetSubjectsAsync();
        }

        private async Task<List<SelectListItem>> GetSubjectsAsync()
        {
            List<SelectListItem> listIItems = new List<SelectListItem>();

            List<Subject> items = await _subjectRepository.GetItemsAsync("name", SortOrder.Ascending, "", 1, 1000);

            listIItems = items.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();

            SelectListItem defItem = new SelectListItem()
            {
                Text = "---Select Subject---",
                Value = ""
            };

            listIItems.Insert(0, defItem);
            return listIItems;
        }

    }
}

Preparations/Preparation/Controllers/SubjectController.cs
using Humanizer.Localisation;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Preparation.Interfaces;
using Preparation.Models;

namespace Preparation.Controllers
{
    public class SubjectController : Controller
    {
        private readonly ISubject _subjectRepository;
        private readonly IQuestion _questionRepository;
        public SubjectController(ISubject subjectRepository, IQuestion questionRepository)
        {
            _subjectRepository = subjectRepository;
            _questionRepository = questionRepository;
        }

        public async Task<IActionResult> Index(string sortExpression = "", string searchText = "", int currentPage = 1, int pageSize = 5)
        {
            SortModel sortModel = new SortModel();
            sortModel.AddColumn("name");
            sortModel.ApplySort(sortExpression);


            PaginatedList<Subject> items = await _subjectRepository.GetItemsAsync(sortModel.SortedProperty, sortModel.SortedOrder, searchText, currentPage, pageSize);

            var pager = new PagerModel(items.TotalRecords, currentPage, pageSize);
            pager.SortExpression = sortExpression;
            pager.SearchText = searchText;

            ViewBag.Pager = pager;

            ViewData["SortModel"] = sortModel;
            ViewBag.SearchText = searchText;

            TempData["SearchText"] = searchText;
            TempData.Keep("SearchText");

            TempData["PageSize"] = pageSize;
            TempData.Keep("PageSize");

            TempData["CurrentPage"] = currentPage;
            TempData.Keep("CurrentPage");

            return View(items);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var item = new Subject();

            PopulateViewBagsAsync().GetAwaiter().GetResult();

            return View(item);
        }

        [HttpPost]
        public async Task<IActionResult> Create(Subject subject)
        {
            if(ModelState.IsValid)
            {
                await _subjectRepository.GreateAsync(subject);
                await PopulateViewBagsAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(subject);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var item = await _subjectRepository.GetItemAsync(id);

            if(item != null)
            {
                await PopulateViewBagsAsync();

                return View(item);
            }

            return NotFound();          
        }

        [HttpPost]
        public async Task<IActionResult> Edit(Subject subject)
        {
            if (ModelState.IsValid)
            {
                await _subjectRepository.EditAsync(subject);

                await PopulateViewBagsAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(subject);
        }


        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var item = await _subjectRepository.GetItemAsync(id);

            if (item != null)
            {
                return View(item);
            }

            return NotFound();
        }

        [HttpPost]
        public async Task<IActionResult> Delete(Subject subject)
        {
            if (ModelState.IsValid)
            {
                await _subjectRepository.DeleteAsync(subject);
                return RedirectToAction(nameof(Index));
            }

            return View(subject);
        }


        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var item = await _subjectRepository.GetItemAsync(id);

            if (item != null)
            {
                return View(item);
            }

            return NotFound();
        }


        private async Task PopulateViewBagsAsync()
        {
            ViewBag.Questions = await GetQuestionsAsync();
        }

        private async Task<List<SelectListItem>> GetQuestionsAsync()
        {
            List<SelectListItem> listIItems = new List<SelectListItem>();

            List<Question> items = await _questionRepository.GetItemsAsync("name", SortOrder.Ascending, "", 1, 1000);

            listIItems = items.Select(x => new SelectListItem()
            {
                Text = x.Name,
                Value = x.Id.ToString()
            }).ToList();

            SelectListItem defItem = new SelectListItem()
            {
                Text = "---Select Subject---",
                Value = ""
            };

            listIItems.Insert(0, defItem);
            return listIItems;
        }

    }
}

Preparations/Preparation/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Preparation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Preparation.styles.css" asp-append-version="true" />
</head>

@{
    string menuTextColor = "text-dark";
}

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Preparation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="dropdown nav-item pr-2">
                            <a class="nav-link dropdown-toggle @menuTextColor" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                Master
                            </a>
                            <ul class="dropdown-menu" style="background:linear-gradient(to right,#ffffff,#A9A9A9)">
                                <li class="nav-item">
                                    <a class="nav-link @menuTextColor" asp-area="" asp-controller="Subject" asp-action="Index">Subjects</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link @menuTextColor" asp-area="" asp-controller="Question" asp-action="Index">Questions</a>
                                </li>
                            </ul>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Preparation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>